name: build

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js for semantic-release
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Try to find the next version
        id: version
        run: |
          yarn install
          npm_config_yes=true npx semantic-release --dry-run
          run: echo ::set-output name=version::$(cat VERSION)
          rm -f .VERSION

      - name: Dummy step that should be considered extension build
        run: |
          echo "VERSION --->>>> "
          echo ${{ steps.version.outputs.version }}
          mkdir extension
          cp package.json extension/package.json
          cp manifest.json extension/manifest.json
          cp README.md extension/README.md
          touch extension/build_output.txt

      - name: Semantic release
        run: |
          yarn install
          npm_config_yes=true npx semantic-release
          cat package.json
          cat manifest.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension
          path: extension/
          retention-days: 5
          if-no-files-found: error
